# Deployment postgre
apiVersion: app/v1
kind: Deployment
metadata:
  name: postgre
spec: 
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      container:
        - name: postgre
          image: postgres:13.16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value:  fakeshop
            - name: POSTGRES_USER
              value: fakeshop
            - name: POSTGRES_PASSWORD
              value: database12345
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetport: 5432
---
# Deployment app web
apiVersion: app/v1
kind: Deployment
metadata:
  name: fakeshop
spec: 
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      container:
        - name: fakeshop
          image: veronicaluerce/fake-shop:v1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value:  postgre
            - name: DB_USER
              value: fakeshop
            - name: DB_PASSWORD
              value: database12345
            - name: DB_NAME
              value: fakeshop
            - name: FLASK_APP
              value: index.py
---
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
    - port: 80
      targetport: 5000
  type: LoadBalancer